Repository w3c/echidna, pull requests merged in 2018-11, with the labels that each got.

#615 check that the 'This Version' url does match the regex before extracting the shortname
  lib/mailer.js
Labels: bug

#616 Package node-uuid is deprecated; use uuid instead
  app.js
  package.json
Labels: bug, security, testing

#619 Use new "W3C_API_KEY" for Specberus in Travis builds
  .travis.yml
Labels: testing
