Repository w3c/echidna, pull requests merged in 2018-04, with the labels that each got.

#547 Fix tests after switch to process 2018
  test/drafts/nav-csserror/meta.json
  test/drafts/nav-csswarning/meta.json
Labels: bug, testing

#551 fix(package): update request to version 2.85.0
  package.json
Labels: greenkeeper

#540 fix(package): update file-type to version 7.6.0
  package.json
Labels: greenkeeper

#548 fix(package): update moment to version 2.22.0
  package.json
Labels: greenkeeper

#552 Update link to live version of Specberus
  views/index.html
Labels: UI, bug

#559 fix(package): update file-type to version 7.7.1
  package.json
Labels: greenkeeper

#560 fix(package): update tar-stream to version 1.6.0
  package.json
Labels: greenkeeper
